import json
import os
import random
import time
import google.generativeai as genai
from datetime import datetime, timedelta

# --- 1. 配置 ---
GEMINI_KEY = os.environ.get("GEMINI_API_KEY")

# 如果没有 Key，打印警告但继续运行（使用假数据）
if GEMINI_KEY:
    try:
        genai.configure(api_key=GEMINI_KEY)
        print("✅ Gemini API Key found and configured.")
    except Exception as e:
        print(f"❌ Gemini Configuration Error: {e}")
else:
    print("⚠️ WARNING: No GEMINI_API_KEY found. Using fallback data only.")

SITES_FILE = 'sites.json'

# --- 2. 数据生成函数 ---

def get_fallback_news():
    """兜底新闻数据（当 AI 失败时使用）"""
    return [
        {
            "title": "World Cup 2026: Automatic Update System Live",
            "date": datetime.now().strftime("%b %d, %Y"),
            "excerpt": "This content was generated by the fallback system because AI generation failed or was skipped. System is operational."
        },
        {
            "title": "Betting Odds Update: Brazil vs France",
            "date": datetime.now().strftime("%b %d, %Y"),
            "excerpt": "Live odds are being updated. Check back shortly for the latest spreads and moneyline moves."
        },
        {
            "title": "New Payment Methods Added",
            "date": datetime.now().strftime("%b %d, %Y"),
            "excerpt": "We have added new crypto options for faster withdrawals. Bitcoin and USDT now accepted."
        }
    ]

def generate_ai_content(domain, theme):
    """尝试用 AI 生成，如果失败则返回兜底数据"""
    if not GEMINI_KEY:
        return get_fallback_news(), "AI Key missing. This is fallback SEO text."

    print(f"🤖 Asking Gemini to write for {domain}...")
    try:
        model = genai.GenerativeModel('gemini-1.5-flash')
        
        # 生成新闻
        prompt = f"""
        You are a content generator for a {theme} betting site: {domain}.
        Output a JSON array of 3 news items about World Cup 2026.
        Format: [{{"title": "...", "date": "...", "excerpt": "..."}}]
        STRICT JSON ONLY. NO MARKDOWN.
        """
        response = model.generate_content(prompt)
        text = response.text.replace('```json', '').replace('```', '').strip()
        news_data = json.loads(text)
        
        # 生成 SEO
        seo_resp = model.generate_content(f"Write 1 sentence SEO description for {domain}.")
        seo_text = seo_resp.text.strip()
        
        return news_data, seo_text

    except Exception as e:
        print(f"❌ AI Generation Failed: {e}")
        return get_fallback_news(), f"Error generating content for {domain}. Fallback text active."

def generate_matches():
    """生成模拟赛事数据"""
    matches = []
    teams = ["Mexico", "USA", "Canada", "Brazil", "Argentina", "France", "Spain", "Japan"]
    stadiums = ["Azteca", "MetLife", "SoFi", "BC Place"]
    
    today = datetime.now()
    for i in range(3):
        t1, t2 = random.sample(teams, 2)
        matches.append({
            "team_a": t1,
            "team_b": t2,
            "date": (today + timedelta(days=i+1)).strftime("%b %d - 20:00"),
            "stadium": random.choice(stadiums),
            "odds": f"{random.uniform(1.5, 3.5):.2f}"
        })
    return matches

def generate_partners():
    """生成合作伙伴 Logo"""
    return [
        "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Mastercard-logo.svg/200px-Mastercard-logo.svg.png",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/PayPal.svg/200px-PayPal.svg.png",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/100px-Apple_logo_black.svg.png",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Visa_Inc._logo.svg/200px-Visa_Inc._logo.svg.png"
    ]

# --- 3. 主程序 ---

def main():
    print("🚀 Agent Starting...")
    
    # 读取 sites.json
    if not os.path.exists(SITES_FILE):
        print(f"❌ Error: {SITES_FILE} not found!")
        return

    with open(SITES_FILE, 'r') as f:
        try:
            sites = json.load(f)
        except json.JSONDecodeError:
            print("❌ Error: sites.json is not valid JSON.")
            return

    print(f"📂 Found {len(sites)} sites to update.")

    # 遍历更新
    for site in sites:
        domain = site.get('hostname', 'Unknown Domain')
        print(f"👉 Processing: {domain}")
        
        # 1. 强制写入 Hero (如果没有)
        if 'hero' not in site:
            site['hero'] = {
                "title": f"Official {domain} Hub",
                "subtitle": "Live Odds, News & Exclusive Offers",
                "cta_text": "Get Bonus",
                "background_image": "https://images.unsplash.com/photo-1522770179533-24471fcdba45?auto=format&fit=crop&w=1920&q=80"
            }
        
        # 2. 生成新闻 (AI 或 兜底)
        news, seo = generate_ai_content(domain, site.get('theme', 'modern'))
        site['news_data'] = news
        
        if 'seo_content' not in site: site['seo_content'] = {}
        site['seo_content']['body'] = seo
        site['seo_content']['title'] = f"Guide for {domain}"

        # 3. 生成赛事
        site['matches_data'] = generate_matches()
        
        # 4. 生成合作伙伴
        site['partners_data'] = generate_partners()
        
        # 5. 确保 layout_order 完整
        site['layout_order'] = ["hero", "matches", "offers", "news", "partners", "seo"]
        
        # 6. 确保 offer_ids 存在 (防止空白)
        if 'offer_ids' not in site:
             site['offer_ids'] = ["test_1", "test_2"]

        # 休息一下
        time.sleep(2)

    # 保存
    with open(SITES_FILE, 'w') as f:
        json.dump(sites, f, indent=2)
    
    print("✅ SUCCESS: sites.json updated with content!")

if __name__ == "__main__":
    main()
